### ISSUE TITLE
Better Questing Party Quests Not Syncing

### ISSUE THREAD

**Issue by NovaBomber** [NillerMedDild/Enigmatica2Expert#1336]
**Modpack version**
1.68

**Can the issue be reproduced?**
unknown

**Logs**
Not applicable

**Issue**
Better Questing party quest completion will not sync amongst players in the party. If I complete a quest, my friends in the party don't get that completion. It's like better questing doesn't realize we are in a party or something

**Comment by NillerMedDild** [comment]
Please update to 1.69 and see if it persists :)

**Comment by NovaBomber** [comment]
I do not see version 1.69 on CurseForge's website, GitHub, or in the twitch launcher. I may be missing something.

**Comment by NillerMedDild** [comment]
Oh my bad, we will look into the issue :)

**Comment by NovaBomber** [comment]
I completely forgot to mention this, and I feel like I should, the server is my own; it's running off of my computer. I used the server files provided.

**Comment by NillerMedDild** [comment]
Is the BQ version in PO3 the same?

**Comment by NovaBomber** [comment]
They are indeed on the same version, 3.5.300

**Comment by NillerMedDild** [comment]
Would you mind updating to the latest BQ version and check that? :)

**Comment by NovaBomber** [comment]
I updated to the latest version, 3.5.309 and it appears to still not work.

**Comment by NillerMedDild** [comment]
Did you also update Standard Expansion btw?

**Comment by NillerMedDild** [comment]
https://github.com/Funwayguy/BetterQuesting/issues/553 Linking for good meassure, have not re-opened yet.

**Comment by NillerMedDild** [comment]
Would this in changelogs: 
```
- Shared party progression is currently not active. Functionality will return in a later build in a new form. Existing progress will be honoured however it will revert back to individual input.
```

**Comment by NovaBomber** [comment]
My friends and I decided to play an earlier version of the modpack, version 1.54, which allows party progression. Hopefully, it's added back soon.

**Comment by Yoshy2002** [comment]
Anyone is able to help me too? Having the same Proble as NovaBomber. Im on a Nitrado Server with Friends and ive already completed multiple quests, but if a friend joins my Team in the Quest Book, the Quests doesnt sync for him. Would be nice if anyone could help me!!

**Comment by NillerMedDild** [comment]
That is intended behaviour, you need to be online and in the same team at the same time for quests to sync.

**Comment by Yoshy2002** [comment]
We arew definitely online at the same time and in the same Team and Quest Party, but it still doesnt work for us.

**Comment by NillerMedDild** [comment]
Quests you complete while your team mates are online don't sync?

**Comment by ar1a** [comment]
can confirm, quests don't sync with both of us online and completed while both are online

**Comment by NillerMedDild** [comment]
Could you please try syncing the clocks on the server and your PCs? :)

**Comment by ar1a** [comment]
done that, initially only 2s off but we both synced and got a new
achievement and nothing was synced.

open to LAN server, not dedicated

**Comment by Frikkle** [comment]
There have been issues with BetterQuesting progress not synchronizing properly on LAN setups. @ar1a which version are you playing on? This issue has been reported a while back (see https://github.com/Funwayguy/BetterQuesting/issues/657) and has since been resolved (as far as I know).

If you are also on 1.68, please update to the latest version and see if the issue persists; if it does, please give us some more information and we can continue to investigate from there.

**Comment by NillerMedDild** [comment]
The issue should still exist in 1.75, I haven't updated to latest BQ yet.

**Comment by ar1a** [comment]
i'm on 1.75b
